### ISSUE TITLE
Recommendation to handle values lower than LOD? 

### ISSUE THREAD

**Issue by Shicheng-Guo** [Olink-Proteomics/OlinkRPackage#106]
Hi Olink team, 

I am wondering what's recommendation to handle values lower than LOD? set to NA, set to LOD or just as it is? or we have better approach to handle values which are lower than LOD? 

Thanks. 

Shicheng

**Comment by kristianHoden** [comment]
Hi Shicheng,
It is recommended to keep those values as they are. We have seen trends that those values still contain information. Especially when comparing to values above LOD.

Cheers,

Kristian
