### ISSUE TITLE
OlinkAnalyze lmer issues

### ISSUE THREAD

**Issue by Manonanthini** [Olink-Proteomics/OlinkRPackage#11]
Hi 
I have been working on Olink dataset and I have following issues, 
1.I have patient id, olinkid, uniprot id and other general olink dataset as NPX form.I couldn't understand what to input in 'random' for the olink_lmer function. I tried different covariates like AGE,BMI, and also Patient id, groupid etc but I got effect effect1:effect2 as NA but effect1 and effect 2 has pvalues and significant or not as output. I have to find lmer fn between disease conditions group and biomarker NPX. What could be the random effets in such simple file?
2.Does the NA or missing values in the sample affect the lmer function? Do I need to remove rows with NA values?
3. Does imputation needed for perfect analysis?
4. Do i can run olink_lmer() without 'random' ?  
Thank you.

regards
Mano

**Comment by kathy-nevola** [comment]
Hi Mano,
I'm sorry you are having difficulties with the olink_lmer() function. The olink_lmer() function is for running linear mixed-effect models for each protein and the random argument corresponds to the column or columns for which you want to model a random effect. 

For example, if you had multiple measurements from each patient and wanted to look at the effect of time on NPX for each protein, then you would fit the model with PatientID as a random effect as you would expect measurements from the same patient to be correlated. Another example of a random effect would be if there was data from multiple sites and you wanted to adjust for the correlation within sites.  I am uncertain of the experimental design from your example, so unfortunately I am unsure what the random effect would be in your model or if a linear mixed-effect model is the right model for your analytical question. 

As for your other questions, NA or missing values do not need to be removed, the function will remove samples with missing variable or covariate levels. You also do not need to do any imputation to run the analysis. However, to use the olink_lmer() function, the df, variable, and random arguments need to be specified.

I hope this helps answer your questions. If you have questions about experimental design and statistical analysis, you can also reach out to biostat@olink.com. Have a great day!

Thanks,
Kathy (they/them)
Data Scientist at Olink Proteomics

**Comment by hehetwish** [comment]
Hi, 
I hope this finds you well.
I used the olink_lmer() function, it worked and the model ran smoothly, although I have a single measurement from each patient. 
However, when it comes to running the post hoc test for the model, I had an error that couldn't ride of. 
Error in lme4::lFormula(formula = as.formula(formula_string), data = data,  : 
  0 (non-NA) cases

Can you please help? 
Many thanks 
Hanan

**Comment by skchronicles** [comment]
@kathy-nevola I have a quick question. What exactly do you mean by `Site`?

**Comment by tom-snir** [comment]
@skchronicles I believe they are referring to an experimental/physical site, so for example if the data came from several different research centers/countries. The site might affect the data, but this would be a random effect and should be modeled that way.
