### ISSUE TITLE
TNF, IL6 and CXCL8 in 4 panels 

### ISSUE THREAD

**Issue by Shicheng-Guo** [Olink-Proteomics/OlinkRPackage#113]
Dear Sir/Madam,

Since TNF, IL6, and CXCL8 occur in 4 panels, how to handle the repeat measurement? Average/median or analyze separately? Is there any recommendation from your experience?

Thanks

Shicheng

**Comment by kathy-nevola** [comment]
Sorry for the delay. We recommend analyzing these assays separately. For more information on the application of our assay, please reach out to Support@olink.com or biostat@olink.com.
