### ISSUE TITLE
Epitope effects on pQTL caused by antibody-missense genetic variants

### ISSUE THREAD

**Issue by Shicheng-Guo** [Olink-Proteomics/OlinkRPackage#131]
Dear Olink Team, 

Is there any publication to discuss epitope effects on pQTL caused by antibody-missense genetic variants with Olink technique? 

Thanks. 

Shicheng

**Comment by kathy-nevola** [comment]
Hi Shicheng,

If you email support@olink.com they will be able to connect you with someone who can answer your question. This forum is for issues and support with the Olink Analyze package.

Thanks,
Kathy
