### ISSUE TITLE
Better documentation in Friedman tests

### ISSUE THREAD

**Issue by khkk378** [Olink-Proteomics/OlinkRPackage#160]
If you have removed assays with QC flags so that all assays are no longer measured in all subjects you get the message `not an unreplicated complete block design` from `friedman.test`.  The help text for `olink_one_non_parametric` reads, at least to me, as if though this will be dealt with automatically. Same thing with samples missing time points if that is your grouping variable.

**Comment by kathy-nevola** [comment]
Hi @khkk378,

Thanks for your suggestions. We will look into this issue to help make the documentation more intuitive.

Thanks,
Kathy

**Comment by kathy-nevola** [comment]
Updated in PR #171
