### ISSUE TITLE
Check if datasets were normalized with the same approach prior to bridge/subset normalization

### ISSUE THREAD

**Issue by klevdiamanti** [Olink-Proteomics/OlinkRPackage#186]
**Problem**
In a few occasions bridge/subset normalization was underperforming because the original datasets were not normalized with the same approach. E.g. both PC or both intesnity.

**Solution**
To prevent the above from happenning we could use the column "Normalization" to check in the function whether the input datsets are intensity normalized. If not throw an error/warning.

**Comment by kathy-nevola** [comment]
Linked to OA-185 in Jira
