### ISSUE TITLE
read_NPX fails on data from Olink NPX Manager 2.0.1.175

### ISSUE THREAD

**Issue by ge11232002** [Olink-Proteomics/OlinkRPackage#2]
There are two additional columns of "QC Deviation from median".
I made a quick ugly fix with 8c7a1be6262996a9b3ae58b52e10f586a9e1c9b0 for my data.
A more robust way of determing the number of panels is desired.

**Comment by marisand** [comment]
The read_NPX function is written to not have any other columns than assays, Plate ID and QC warnings which is the standard output. Any other added columns than that will cause the function to fail. Current recommendation is to remove any additional columns before using the function. We will specify this clearly in the help for the function.

**Comment by ge11232002** [comment]
As I confirmed with the operator, QC data (the columns I mentioned) is selected by fault in the export process. Ideally `read_NPX()` should be able to handle all sorts of export options from Olink NPX Manager, instead of demanding manual removal of additional columns.

**Comment by marisand** [comment]
Agreed, we will incorporate it in our next release of OlinkAnalyze. Thanks for your feedback!

**Comment by ACMGlueck** [comment]
I probably ran into the same general problem @ge11232002 mentioned above, but it seems to me that the details may differ.  The error that I got with `read_NPX()` was:
`Error: Must use integers to index columns with `[`:`
`* Position 1 equals 99.8723404255319`
`* Position 2 equals 100.936170212766`
The Excel file that I used comes from Olink NPX Manager. It has the additional two "QC Deviation from median" columns, but there's another problem: `read_NPX()` seems to expect the assay data to go from column 2 to column 93, whereas in my Excel file they go from column 2 (IL8) to column 97 (CSF-1; this is the IMMUNO-ONCOLOGY(v.3111) panel). This means that four data columns get lost in the `panel_data[[i]] <- dat[, (2 + ((i - 1) * 92)):(93 + ((i - 1) * 92))]` step.
Finally, another comment: the format clarification meant to go into the help for `read_NPX()` isn't there yet.

**Comment by marisand** [comment]
Correct. We have now updated the read_NPX function to take

**Comment by ACMGlueck** [comment]
Dear Marianne,
Thank you for the update which indeed addresses the QC deviation column problem - but which unfortunately still gives me a `read_NPX()` error:
`Error: Must use integers to index columns with `[`:`
`* Position 1 equals 97.9148936170213`
`* Position 2 equals 98.9574468085106`
`* Position 4 equals 101.042553191489`
I think the trouble starts with the calculation of the number of panels in this line of `read_NPX()`:
`nr_panel <- (ncol(meta_dat) - 1 - NR_DEVIATIONS)/94`
Even with the inclusion of `NR_DEVIATIONS` I don't get an integer returned; for this, division would have to be by 98. So something is wrong with the `94` assumption.
The line that causes the error is `QC_list[[i]] <- dat.....` as here the column indices are not integers. But there is a deeper problem: The assumption that columns 94 and 95 (or 94 to 97) contain quality controls.  In the case of my IMMUNO-ONCOLOGY(v.3111) data, this is not so; the controls are in columns 5, 20, 47 and 48.
I am afraid that you will have to update `read_NPX()` to explicitly look for the control and data columns to extract the respective data correctly. And that may also be needed to correctly assign the Plate ID, QC Warning and QC Deviation from median columns (and any other columns which Olink NPX Manager might write). Once these columns have been identified, you should also arrive at the correct divisor for `nr_panel <- (ncol(meta_dat) - 1 - NR_DEVIATIONS)/94`.
I hope this helps debug your package.
Anton

**Comment by marisand** [comment]
Dear Anton, 
Thanks for your input! 
We are aware that the read_NPX does not take the control assays at the moment. This is because they do not have a valid OlinkID and we need to change the other functions to take this into account before applying any statistical tests. You should be able to use this read_NPX for all wide versions of the Excel export from NPXM except for the control assays. We are currently working on the first full release of OlinkAnalyze where you will be able to use read_NPX for the full export. We are aiming for a full release in early summer.

**Comment by ACMGlueck** [comment]
Dear Marianne,
Thank you for this heads-up. I am looking forward to the full release.
Best wishes,
Anton
