### ISSUE TITLE
olink_ttest levels

### ISSUE THREAD

**Issue by wangjiawen2013** [Olink-Proteomics/OlinkRPackage#214]
Hi,
When a variable is provided to the olink_ttest function, olink_test sets the first factor level  to be the reference and subsequent levels are compared against this reference by default. However, sometimes the reference is the second level, how to change the reference by releveling the factor in such a situation ?

**Comment by MasoumehSheikhi** [comment]
Hi @wangjiawen2013!

Thank you for reaching out. I have an example demonstrating the answer to your question.

`library(dplyr)
library(OlinkAnalyze)

npx_df_1 <- npx_data1 %>% filter(!grepl('control',SampleID, ignore.case = TRUE))

ttest_results_1 <- olink_ttest(df=npx_df_1,
                             variable = 'Treatment',
                             alternative = 'two.sided')

npx_df_2 <- npx_df |> mutate(Treatment=relevel(factor(Treatment),'Untreated')) 
ttest_results_2 <- olink_ttest(df=npx_df_2,
                             variable = 'Treatment',
                             alternative = 'two.sided')
`
`npx_df_2 ` is the data set with switched reference level.

Please let us know if you if this example did not answer your question or you have further questions.

Bests,
May
