### ISSUE TITLE
Olink annotation database

### ISSUE THREAD

**Issue by Shicheng-Guo** [Olink-Proteomics/OlinkRPackage#215]
Dear Team, 

Is there any database to collect all public Olink data from different diseases.

Thanks 

Shicheng

**Comment by kathy-nevola** [comment]
Hi Shicheng,

I recommend checking out Olink Insight for access to Olink publications and public data: https://insight.olink.com/

Is this sort of what you are looking for?

Thanks,
Kathy

**Comment by kathy-nevola** [comment]
I am closing the issue but feel free to let us know if there is anything else we can do to help.
