### ISSUE TITLE
olink_lmer_posthoc

### ISSUE THREAD

**Issue by M4artin** [Olink-Proteomics/OlinkRPackage#249]
Hi!

Thanks for an easy-to-use package. 

I sometimes get the following error message when running olink_lmer_posthoc() function:
Error in `dplyr::rename()`:
! Can't rename columns that don't exist.
✖ Column `lower.CL` doesn't exist.

Works
`olink_lmer_posthoc(df,
     olinkid_list = lmer_results_twoway_significant,
     variable = c('Response', 'Sampling'),
     random = 'Patient',
     effect = 'Response')`

Works:
`olink_lmer_posthoc(df,
     olinkid_list = lmer_results_twoway_significant,
     variable = c('Response', 'Sampling'),
     random = 'Patient',
     effect = 'Sampling')`

Works:
`olink_lmer_posthoc(df,
     olinkid_list = lmer_results_twoway_significant,
     variable = c('Response', 'Treatment'),
     random = 'Patient',
     effect = 'Sampling')`

Error:
`olink_lmer_posthoc(df,
     olinkid_list = lmer_results_twoway_significant,
     variable = c('Response', 'Sampling_Treatment'),
     random = 'Patient',
     effect = 'Response')`

The 'Response' column only contains two levels, whereas the 'Sampling' contains 4 levels, 'Treatment' 5 levels, and 'Sampling_Treatment' 15. Given the high number of comparisons or missing data points in the clinical data ('Sampling' has samples with e.g. 2 levels as well), is it purely the result of it not being computed due to the construction of the formula?

▆
  1. ├─OlinkAnalyze::olink_lmer_posthoc(...)
  2. │ ├─base::withCallingHandlers(...)
  3. │ └─... %>% ...
  4. ├─dplyr::select(., Assay, OlinkID, UniProt, Panel, term, everything())
  5. ├─dplyr::mutate(., term = paste(effect, collapse = ":"))
  6. ├─dplyr::ungroup(.)
  7. ├─dplyr::group_modify(...)
  8. ├─dplyr:::group_modify.grouped_df(...)
  9. │ ├─dplyr::group_map(.data, fun, .keep = .keep)
 10. │ └─dplyr:::group_map.data.frame(.data, fun, .keep = .keep)
 11. │   └─dplyr:::map2(chunks, group_keys, .f, ...)
 12. │     └─base::mapply(.f, .x, .y, MoreArgs = list(...), SIMPLIFY = FALSE)
 13. │       └─dplyr (local) `<fn>`(dots[[1L]][[1L]], dots[[2L]][[1L]])
 14. │         └─OlinkAnalyze (local) .f(.x, .y, ...)
 15. │           └─OlinkAnalyze:::single_posthoc(...)
 16. │             └─... %>% dplyr::arrange(Adjusted_pval)
 17. ├─dplyr::arrange(., Adjusted_pval)
 18. ├─dplyr::select(., -SE, -df, -t.ratio)
 19. ├─dplyr::rename(., conf.low = lower.CL, conf.high = upper.CL)
 20. ├─dplyr:::rename.data.frame(., conf.low = lower.CL, conf.high = upper.CL)
 21. │ └─tidyselect::eval_rename(expr(c(...)), .data)
 22. │   └─tidyselect:::rename_impl(...)
 23. │     └─tidyselect:::eval_select_impl(...)
 24. │       ├─tidyselect:::with_subscript_errors(...)
 25. │       │ └─rlang::try_fetch(...)
 26. │       │   └─base::withCallingHandlers(...)
 27. │       └─tidyselect:::vars_select_eval(...)
 28. │         └─tidyselect:::walk_data_tree(expr, data_mask, context_mask)
 29. │           └─tidyselect:::eval_c(expr, data_mask, context_mask)
 30. │             └─tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
 31. │               └─tidyselect:::walk_data_tree(new, data_mask, context_mask)
 32. │                 └─tidyselect:::as_indices_sel_impl(...)
 33. │                   └─tidyselect:::as_indices_impl(...)
 34. │                     └─tidyselect:::chr_as_locations(x, vars, call = call, arg = arg)
 35. │                       └─vctrs::vec_as_location(...)
 36. └─vctrs (local) `<fn>`()
 37.   └─vctrs:::stop_subscript_oob(...)
 38.     └─vctrs:::stop_subscript(...)
 39.       └─rlang::abort(...)

best
Martin

**Comment by kathy-nevola** [comment]
Hi Martin,

Thanks so much for your question. Does every level of Sampling_Treatment have samples with both levels of Response? It may be that there is a contrast that cannot be computed in the pairwise posthoc. 

Thanks,
Kathy

**Comment by M4artin** [comment]
Thanks Kathy!

Yes, I suspected it to be on my end. I checked the clinical file and found that one of the combinations only had one level in the Response variable. 

Thanks for such a fast response,
Martin

**Comment by kathy-nevola** [comment]
No problem! Glad I could help!
