### ISSUE TITLE
PRIDE Archive integration with Olink

### ISSUE THREAD

**Issue by ypriverol** [Olink-Proteomics/OlinkRPackage#281]
I'm the team coordinator of PRIDE team ([www.ebi.ac.uk/pride/](http://www.ebi.ac.uk/pride/)), the
largest proteomics database, part of ProteomeXchange. We have multiple users asking us to submit Olink data to PRIDE, something is not yet supported. I found this repository from Olink open in github and want to contact you for help. 

We are modeling now how in PRIDE, how Olink data should look like, this is the first prototype: 

```
Olink:
RAW data:
         .bcl: raw data

Configuration Files:
         .plt: Detector setup file (.plt) from[ https://www.olink.com/members-site/](https://www.olink.com/members-site/) (which PLT file to use is stated on the lot configuration sheet)

Search results:
         .xlsx/txt: search results and quantification results in Excel files
Examples:
          https://figshare.com/articles/dataset/olink_ChipRun_IIM_raw_data/19367111
```

These are the requested files we are planning to ask the submitters for the community to be able to reproduce the results. Can you give us some feedback or help us about which data we should ask. 

Thanks a lot in advance. 
Yasset

**Comment by ypriverol** [comment]
yperez@ebi.ac.uk

Thanks in advance

**Comment by kathy-nevola** [comment]
Closing issue since conversation has moved to email.
