### ISSUE TITLE
olink_normalization() bug

### ISSUE THREAD

**Issue by ACMGlueck** [Olink-Proteomics/OlinkRPackage#3]
Dear Marianne and Christoffer,
First of all, thank you very much for this very useful package. It really made a big leap forward with version 1.0.
Second though, I want to report a bug. For a current analysis, my colleague and I want to normalize samples from two studies using bridging samples.  However, we ran into an error. This error also turned up when running the normalization example from your README documentation:
```
bridge_samples <- intersect(x = npx_data1$SampleID,
                            y = npx_data2$SampleID)
bridge_normalized_data <- olink_normalization(df1 = npx_data1,
                                              df2 = npx_data2,
                                              overlapping_samples_df1 = bridge_samples,
                                              df1_project_nr = "20200001",
                                              df2_project_nr = "20200002",
                                              reference_project = "20200001")
Bridging normalization with overlapping samples will be performed.
Error: Each row of output must be identified by a unique combination of keys.
Keys are shared for 8832 rows:
* 3681, 3695
* 3701, 3715
* 16561, 16575
* 16581, 16595
* 16601, 16615
* 16621, 16635
* 16641, 16655
* 16661, 16675
* 16681, 16695
* 16701, 16715
* 16721, 16735
* 16741, 16755
* 16761, 16775
* 16781, 16795
* 16801, 16815
* 16821, 16835
* 16841, 16855
* 16861, 16875
* 16881, 16895
* 16901, 16915
* 16921, 16935
* 16941, 16955
* 16961, 16975
* 16981, 16995
* 17001, 17015
* 17021, 17035
* 17041, 17055
* 17061, 17075
* 17081, 17095
* 17101, 17115
* 17121, 17135
* 17141, 17155
* 17161, 17175
* 17181, 17195
* 17201, 17215
* 17221, 17235
* 17241, 17255
* 17261, 17275
* 17281, 17295
* 17301, 17315
* 17321, 17335
* 17341, 17355
* 17361, 17375
* 17381, 17395
* 17401, 17415
* 17421, 17435
* 17441, 17455
* 17461, 17475
* 17481, 17495
* 17501, 17515
* 17521, 17535
* 17541, 17555
* 17561, 17575
* 17581, 17595
* 17601, 17615
* 17621, 17635
* 17641, 17655
* 17661, 17675
* 17681, 17695
* 17701,
```
This happens with package version 1.0.2 and R version 3.6 on a CentOS 7 machine.
As minor issues, I’d like to point out that the normalization help page example does not match the README example and has these problems:
1: it tries to read files not supplied with the package:
`data_1 <- read_NPX("~/NPX data1.xlsx")`
`data_2 <- read_NPX("~/NPX data2.xlsx")`
2: the line to find overlapping samples does not work as given (the SampleID columns should be specified):
`overlap_samples<-intersect(data_1,data_2)`
Best regards,
Anton

**Comment by jbarbagallo** [comment]
Hello Anton,

My sincere apologies for taking so long to get back to you on this.

This error is because your overlapping/bridge samples vector includes our Olink Controls. You want to filter those out first, before using intersect().
 
So, for example:
 
df <- npx_data1 %>% filter(!str_detect(SampleID,'CONTROL*.'))
 
bridge_samples <- intersect(x = df$SampleID,
                            y = npx_data2$SampleID)
 
bridge_normalized_data <- olink_normalization(df1 = npx_data1,
                                              df2 = npx_data2,
                                              overlapping_samples_df1 = bridge_samples,
                                              df1_project_nr = "20200001",
                                              df2_project_nr = "20200002",
                                              reference_project = "20200001")
 
 
We use our Olink controls to assess run performance and calculate CVs, but we don’t use them in bridge normalization, even though they are run on all plates. Please let us know if you need help with anything else!

Best,
Jessica

**Comment by ACMGlueck** [comment]
Hi Jessica,

Thank you for your reply. Indeed it works when removing the control samples.

With kind regards,

Anton
