### ISSUE TITLE
Semi-paired analysis

### ISSUE THREAD

**Issue by tdfy** [Olink-Proteomics/OlinkRPackage#325]
Hello, 
Thank you for the package! 

I am analyzing data with individuals in multiple conditions, however the N is pretty low and analyses could be improved using a semi-paired analysis. To be explicit, Treated condition is 10 individuals, 8 of which are paired in untreated, while two are exclusive to the treated condition. Could you please advise on a test in the package ( or elsewhere ) to address this? Thanks!

-Todd

**Comment by kathy-nevola** [comment]
I would recommend trying olink_ttest or olink_lmer. I believe olink_lmer can handle missing samples from time points (which sounds similar to what you are describing here). Let me know if this works.

Thanks,
Kathy
