### ISSUE TITLE
olink_one_non_parametric and missing timepoints in paired-data

### ISSUE THREAD

**Issue by Lucpen** [Olink-Proteomics/OlinkRPackage#345]
Hi!

First of all, thanks for the OLINK package! 
I have a couple of questions about olink_one_non_parametric:
- I want to compare baseline to 3 different timepoints (samples are paired) but some of the patients are missing one timepoint. I tried using olink_one_non_parametric (Friedmans) but I quickly realised that to use it I would need to remove all patients that were missing one timepoint. I don’t have many samples per timepoint so I want to avoid doing this. Is there a way around this with OLINK package or should I just proceed with using Friedman + postdoc outside of the OLINK package?
- I also wanted to ask if it is possible to use olink_one_non_parametric to compare only some of the timepoints. I have 3 (base, t1, t2 ) timepoints and would only want to compare to baseline (base vs. t1 and base vs. t2).

Thanks again!

**Comment by kathy-nevola** [comment]
Hi @Lucpen.

Unfortunately this function is not able to support missing timepoints. If you want to use this function, then either the timepoint or patients will need to be removed. 

The Olink_lmer function can support subjects with missing timepoints and you can specify the contrasts using an emmeans call. However this function is parametric so it would depend if your data met the assumptions for this test. 

Hopes this helps. If you have any additional questions you can also reach out to biostattools@olink.com for access to our data science team.
Thanks,
Kathy

**Comment by Lucpen** [comment]
Thanks Kathy!
