### ISSUE TITLE
Olink enrichment for olink_ordinalRegression

### ISSUE THREAD

**Issue by karpat90** [Olink-Proteomics/OlinkRPackage#348]
Hello!

I wanted to ask if it is possible to use proteins from olink_ordinalRegression in olink_pathway_enrichment rather than olink_ttest ?

Thank you for a great package!

**Comment by kathy-nevola** [comment]
Hi @karpat90!

Thanks so much for using Olink Analyze. The input for `olink_pathway_enrichment` requires that the `test_results` contain the estimate and Adjusted_pval columns. For models with more than 1 set of contrasts, the data will need to be filtered to 1 contrast, as there can only be 1 set of results for each assay. `olink_ordinalRegression()`, followed by `olink_ordinalRegression_posthoc()` could  be used to generate the `test_result` data frame. In this case the `olinkid_list` argument for `olink_ordinalRegression_posthoc()` should contain all Olink IDs in the NPX data to generate results for all assays.

Hope this helps.
Thanks,
Kathy
