### ISSUE TITLE
Handle gzipped Explore long format csv files

### ISSUE THREAD

**Issue by schaffman5** [Olink-Proteomics/OlinkRPackage#80]
The parser handles the long format of the csv data files from the Explore platform.  However, because of data redundancy and resulting large file sizes, it would be nice if the parser would handle gzipped versions of these csv files directly.

**Comment by kathy-nevola** [comment]
When you mention reading a zipped csv file, are you referring to the zipped file exported from MyData or a zipped version of just the NPX file? Sorry for the delay in responding to your issue.

**Comment by schaffman5** [comment]
Just a gzipped version of the NPX file.

**Comment by kathy-nevola** [comment]
This issue was fixed in PR #115  and has been merged into develop. The resolution will be included in the next release.
